#!/bin/bash

#Empezamos programa
echo "¿Cuantas maquinas quieres que te haga? (1 a 3)"
read NUM
contador=0
#Esto hace que mire las maquinas que tienes
ME=$(ls | grep 'qcow2' | wc -l)
echo  "Usted posee $ME maquinas"
if [ $NUM -eq 1 -o $NUM -eq 2 -o $NUM -eq 3 ]
then
 #Esto hace que si el Num de maquinas es mayor o igual al numero puesto que haga el bucle
if [ $ME -ge $NUM ]
	then
#Bucle que hace maquinas por un contador, cuando ese contador llegue al numero de maquinas, para
		while true
		do
		#Creacion de Macs
			MAC=$(echo "02:"`openssl rand -hex 5 | sed 's/\(..\)/\1:/g; s/.$//'`)
			echo "La mac será $MAC de la maquina $contador"
		#Creacion de maquinas
			kvm -m 512 -hda stretch$contador.qcow2 \
			-device virtio-net,netdev=n0,mac=$MAC \
			-netdev tap,id=n0,ifname=tap$contador,script=no,downscript=no &
		#El contador va incrementando si no es igual al numero de maquinas
			if [ $contador -eq $NUM ]
			then
				echo "Fin del programa"
			else
				contador=$(($contador+1))
			fi
			if [ $contador -eq $NUM ]
			then
				break
			fi
		done
	else
		echo "Usted no tiene maquinas suficientes"
	fi
else
	echo "¿¿Usted piensa destruir su maquina??"
	echo "O simplemente usted es retrasado."
fi
