#!/bin/bash
while true
do
	var2=$(who | awk {'print $5'} | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}')
	for var in `who | awk '{print $2}' | sort | uniq`
	do
		if [ $var != ':0' ]
		then
        		zenity --question --title="Conexion entrante" --text "Han entrado a tu pc $var2" 2 >/dev/null
			if [ $? -eq 0 ]
			then
				pkill -9 -t $var
				zenity --question --title="Bloqueazo" --text "¿Quieres bloquearlo para toda la vida?" 2 >/dev/null
				if [ $? -eq 0 ]
				then
					echo "sshd: $var2" >> /etc/hosts.deny
				fi
			else
				sleep 20
			fi
		fi
	done
	sleep 2
done

